gsap.from("#banner",{
    y:100,
    duration:0.9,
    stagger:0.3,
    delay:0.4,
    opacity:0,
})
gsap.from("#menu",{
    y:200,
    duration:0.9,
    stagger:0.3,
    delay:0.4,
    opacity:0,
})
gsap.from("#img",{
    y:100,
    duration:1,
    stagger:0.3,
    delay:0.6,
    opacity:0,
})